//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public string sid { get; set; }
        public string spass { get; set; }
        public Nullable<short> power { get; set; }
        public string sstate { get; set; }
        public string sname { get; set; }
        public string sclass { get; set; }
        public string sex { get; set; }
        public string stele { get; set; }
    
        public virtual student student1 { get; set; }
        public virtual student student2 { get; set; }
    }
}
